### ISSUE TITLE
Unable to add user

### ISSUE THREAD

**Issue by dolphinau** [kernoeb/jean_racine_bot#4]
Hi!
I recently set up the jean_racine bot in a discord server, but I can't add any user.
The bot keeps telling me the user doesn't exist.
I double checked I'm using the root-me ID and not the pseudo.

**Comment by kernoeb** [comment]
Hello!  
I just tested on my instance, it looks to work 

![image](https://user-images.githubusercontent.com/24623168/187717648-bd7782e7-38f9-4271-a148-3bcff81246a0.png)

Do you have any logs ? 

It'll be easier to talk on Discord if possible --> `kernoeb#7737`

**Comment by dolphinau** [comment]
Solved by regenerating a new API key on root-me.org :+1:
