### ISSUE TITLE
Changing pages in role scoreboards transforms it to global scoreboard

### ISSUE THREAD

**Issue by SmylerMC** [kernoeb/jean_racine_bot#5]
**Changing pages in a role scoreboard resets it and turns it a global one.**

## Environment
Kubernetes deployment.

- Jean Racine image: `ghcr.io/kernoeb/jean_racine_bot:main` (22-10-16 build)
- MongoDB image: `docker.io/bitnami/mongodb:4.4`

## Steps to reproduce:
1. Add Jean Racine to a server, initialize it in a channel.
2. Add a few users with /adduser.
3. Use /sync_user to synchronize Discord and RootMe accounts, with a specific Discord role.
4. Use /scoreboard with one of the previously synchronized roles.
5. Try to go to the second page of the scoerboard. It transforms into a global scoreboard.

**Comment by kernoeb** [comment]
Oops... Good find !
I'll check this as soon as possible 👍

**Comment by kernoeb** [comment]
It should be fixed in this commit : https://github.com/kernoeb/jean_racine_bot/commit/3edabfaecf3cf7593743e5dc3af208901e11cb39

You can `./update.sh`, please tell me if it's working now :)

**Comment by SmylerMC** [comment]
Yes, it's all good now, closing the issue.
Thanks for the quick fix.
